{"name": "User can search for a product", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=131.0.6778.205)\nStacktrace:\n0   chromedriver                        0x00000001021ad268 chromedriver + 7098984\n1   chromedriver                        0x00000001021a513a chromedriver + 7065914\n2   chromedriver                        0x0000000101b49d70 chromedriver + 400752\n3   chromedriver                        0x0000000101b307f4 chromedriver + 296948\n4   chromedriver                        0x0000000101b306e3 chromedriver + 296675\n5   chromedriver                        0x0000000101b4c102 chromedriver + 409858\n6   chromedriver                        0x0000000101bdbb5f chromedriver + 998239\n7   chromedriver                        0x0000000101bbcfb3 chromedriver + 872371\n8   chromedriver                        0x0000000101b8b5c2 chromedriver + 669122\n9   chromedriver                        0x0000000101b8c59e chromedriver + 673182\n10  chromedriver                        0x0000000102172020 chromedriver + 6856736\n11  chromedriver                        0x0000000102176050 chromedriver + 6873168\n12  chromedriver                        0x00000001021543d7 chromedriver + 6734807\n13  chromedriver                        0x00000001021769ee chromedriver + 6875630\n14  chromedriver                        0x0000000102143c14 chromedriver + 6667284\n15  chromedriver                        0x0000000102193778 chromedriver + 6993784\n16  chromedriver                        0x0000000102193936 chromedriver + 6994230\n17  chromedriver                        0x00000001021a4d18 chromedriver + 7064856\n18  libsystem_pthread.dylib             0x00007ff810a86253 _pthread_start + 99\n19  libsystem_pthread.dylib             0x00007ff810a81bef thread_start + 15\n\n", "trace": "  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/search_product_steps.py\", line 20, in verify_search_results\n    context.app.search_product_page.verify_search_results(product)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/pages/search_product_page.py\", line 59, in verify_search_results\n    self.verify_partial_text(product, *self.SEARCH_RESULTS)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/pages/base_page.py\", line 94, in verify_partial_text\n    actual_text = self.find_element(*locator).text\n                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/pages/base_page.py\", line 22, in find_element\n    return self.driver.find_element(*locator)\n           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 766, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Open target main page", "status": "passed", "start": 1735866443161, "stop": 1735866448563}, {"name": "When Search for tide", "status": "passed", "start": 1735866448564, "stop": 1735866463903}, {"name": "Then Verify search result shown for tide", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=131.0.6778.205)\nStacktrace:\n0   chromedriver                        0x00000001021ad268 chromedriver + 7098984\n1   chromedriver                        0x00000001021a513a chromedriver + 7065914\n2   chromedriver                        0x0000000101b49d70 chromedriver + 400752\n3   chromedriver                        0x0000000101b307f4 chromedriver + 296948\n4   chromedriver                        0x0000000101b306e3 chromedriver + 296675\n5   chromedriver                        0x0000000101b4c102 chromedriver + 409858\n6   chromedriver                        0x0000000101bdbb5f chromedriver + 998239\n7   chromedriver                        0x0000000101bbcfb3 chromedriver + 872371\n8   chromedriver                        0x0000000101b8b5c2 chromedriver + 669122\n9   chromedriver                        0x0000000101b8c59e chromedriver + 673182\n10  chromedriver                        0x0000000102172020 chromedriver + 6856736\n11  chromedriver                        0x0000000102176050 chromedriver + 6873168\n12  chromedriver                        0x00000001021543d7 chromedriver + 6734807\n13  chromedriver                        0x00000001021769ee chromedriver + 6875630\n14  chromedriver                        0x0000000102143c14 chromedriver + 6667284\n15  chromedriver                        0x0000000102193778 chromedriver + 6993784\n16  chromedriver                        0x0000000102193936 chromedriver + 6994230\n17  chromedriver                        0x00000001021a4d18 chromedriver + 7064856\n18  libsystem_pthread.dylib             0x00007ff810a86253 _pthread_start + 99\n19  libsystem_pthread.dylib             0x00007ff810a81bef thread_start + 15\n\n", "trace": "  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/search_product_steps.py\", line 20, in verify_search_results\n    context.app.search_product_page.verify_search_results(product)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/pages/search_product_page.py\", line 59, in verify_search_results\n    self.verify_partial_text(product, *self.SEARCH_RESULTS)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/pages/base_page.py\", line 94, in verify_partial_text\n    actual_text = self.find_element(*locator).text\n                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/pages/base_page.py\", line 22, in find_element\n    return self.driver.find_element(*locator)\n           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 766, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"/Users/yevheniiustenko/QA/Yevhenii.Ustenko.python-selenium-automation/.venv/lib/python3.13/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1735866463904, "stop": 1735866463932}], "start": 1735866440770, "stop": 1735866464245, "uuid": "d51c9b47-0baa-4c25-b9d5-55cce4e0a2b1", "historyId": "dc6fb203fb67e7d5fef00a58b27e357f", "fullName": "Tests for search: User can search for a product", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Tests for search"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}